'use server';

import { processMediaToArticle } from './service';
import { writeFile } from 'fs/promises';
import { join } from 'path';
import { revalidatePath } from 'next/cache';
import { ArticleSchema } from '@/lib/schemas';

export async function generateArticleFromMedia(formData: FormData) {
    try {
        const file = formData.get('media') as File;
        if (!file) throw new Error("Aucun fichier fourni");

        // Delegate heavy lifting to service (Node.js context)
        const results = await processMediaToArticle(file);

        const date = new Date().toISOString();
        const createdArticles = [];

        // Iterate over the array of generated articles (Expertise & Storytelling)
        for (const result of results) {
            // Construct the data object for Validation first
            const articleData = {
                title: result.title,
                slug: result.slug,
                date: date,
                category: result.category || 'Podcast',
                subCategory: result.subCategory,
                excerpt: result.excerpt || '',
                tags: result.tags || [],
                imagePrompts: result.imagePrompts || [], // Image prompts generated by AI
                seo: {
                    metaTitle: result.metaTitle || result.title,
                    metaDescription: result.metaDescription || result.excerpt || '',
                    mainKeyword: result.mainKeyword,
                    keywords: result.seoKeywords || []
                }
            };

            // Validate against Schema immediately to catch errors
            const validData = ArticleSchema.parse(articleData);

            // Create Article Draft Content manually
            const fileContent = `---
title: "${validData.title.replace(/"/g, '\\"')}"
date: "${validData.date}"
slug: "${validData.slug}"
category: "${validData.category}"
subCategory: "${validData.subCategory || ''}"
author: "Florian"
coverImage: "/images/placeholder.jpg"
excerpt: "${(validData.excerpt || '').replace(/"/g, '\\"')}"
tags: ${JSON.stringify(validData.tags || [])}
imagePrompts: ${JSON.stringify(validData.imagePrompts || [])}
seo:
  metaTitle: "${(validData.seo?.metaTitle || '').replace(/"/g, '\\"')}"
  metaDescription: "${(validData.seo?.metaDescription || '').replace(/"/g, '\\"')}"
  mainKeyword: "${(result.mainKeyword || '').replace(/"/g, '\\"')}"
  keywords: ${JSON.stringify(validData.seo?.keywords || [])}
---

${result.content} 
`;

            // Save directly to content/articles
            const articlesDir = join(process.cwd(), 'content', 'articles');
            const outputPath = join(articlesDir, `${validData.slug}.mdx`);
            await writeFile(outputPath, fileContent);

            createdArticles.push(validData.slug);
        }

        // Revalidate paths to ensure the new articles are seen
        revalidatePath('/admin');
        revalidatePath('/admin/articles');
        // Revalidate for each slug
        for (const slug of createdArticles) {
            revalidatePath(`/admin/articles/${slug}`);
        }

        return {
            success: true,
            slug: createdArticles[0], // Return the first one for direct redirect, or maybe change frontend to show list
            message: `2 Brouillons créés avec succès : ${createdArticles.join(', ')}`
        };

    } catch (error: any) {
        console.error("Agent Error:", error);
        // Show validation errors clearly
        if (error.issues) {
            return { success: false, error: `Validation Error: ${error.issues.map((i: any) => i.message).join(', ')}` };
        }
        return { success: false, error: error.message || String(error) };
    }
}
